/**
 * WKND Brand Concierge UI export, adapted for the site-wide Sherpa panel.
 * Public styling/content only; datastream configuration stays in martech-config.js.
 */
export default {
  id: '058bda58-c201-48e0-b375-92dbfc631a86',
  name: 'WKND ADVENTURES_26-09-22_058bda58-c201-48e0-b375-92dbfc631a86',
  metadata: {
    brandName: 'WKND ADVENTURES',
    version: '1.0.0',
    language: 'en',
    namespace: 'brand-concierge',
  },
  behavior: {
    multimodalCarousel: { cardClickAction: 'openLink' },
    input: {
      enableVoiceInput: false,
      continuousVoiceMode: false,
      disableMultiline: true,
      showAiChatIcon: true,
    },
    chat: { messageAlignment: 'normal', messageWidth: '100%' },
    privacyNotice: {
      title: 'Privacy Notice',
      text: 'Your use of this automated chatbot constitutes your consent that the personal information you provide in the chat session can be collected, used, disclosed, and retained by WKND Adventures and service providers acting on WKND Adventures\' behalf in accordance with the {Privacy Policy}. Please do not provide sensitive personal information (such as financial or health information) in the chatbot.',
      links: [{
        text: 'Privacy Policy',
        url: 'https://wknd-adventures.run.place/privacy-and-terms',
      }],
    },
    meetingForm: {
      fieldsPerRow: 2,
      fieldLayoutRules: {
        textInputs: {
          allowTwoColumns: true,
          fieldTypes: ['string', 'email', 'tel', 'number'],
          identifyBy: null,
        },
        dropdowns: { allowTwoColumns: false, fieldTypes: ['select'], identifyBy: 'hasOptions' },
        checkboxes: { allowTwoColumns: false, fieldTypes: ['boolean', 'checkbox'], identifyBy: null },
      },
      title: { text: 'Request a Meeting', alignment: 'left' },
      subtitle: { text: 'Let us help you plan your next adventure.', alignment: 'left' },
      buttons: {
        submit: { text: 'Submit', alignment: 'left' },
        cancel: { text: 'Cancel', alignment: 'left' },
      },
    },
    calendarWidget: {
      title: { text: 'Schedule Your Adventure', alignment: 'left' },
      subtitle: { text: 'Pick a time that works for you.', alignment: 'left' },
      postTitle: {
        text: 'Once confirmed, you will receive a calendar invite with all the details. The specialist will already have this conversation context, so no need to repeat anything. Looking forward to connecting you with the right expert!',
        alignment: 'left',
      },
      buttons: {
        confirm: { text: 'Confirm', alignment: 'left' },
        cancel: { text: 'Cancel', alignment: 'left' },
      },
    },
    productCard: { actionButtonSize: 'S' },
    b2bLiveChat: { enabled: true },
  },
  disclaimer: {
    text: 'WKND Adventures is committed to protecting your privacy. By using this service, you agree to our {Terms of Use}.',
    links: [{
      text: 'Terms of Use',
      url: 'https://wknd-adventures.run.place/privacy-and-terms',
    }],
  },
  text: {
    'welcome.heading': 'Meet WKND Sherpa',
    'welcome.subheading': 'Your guide to bold stories, real life, and wild places.',
    'input.placeholder': 'Ask Sherpa about your next adventure',
    'input.messageInput.aria': 'Type your message',
    'input.send.aria': 'Send message',
    'input.aiChatIcon.tooltip': 'Chat with WKND Sherpa',
    'input.mic.aria': 'Use voice input',
    'card.aria.select': 'Select this option',
    'carousel.prev.aria': 'Previous',
    'carousel.next.aria': 'Next',
    'scroll.bottom.aria': 'Scroll to bottom',
    'error.network': 'Network error. Please try again.',
    'loading.message': 'Loading your response...',
    'feedback.dialog.title.positive': 'Positive Feedback',
    'feedback.dialog.title.negative': 'Negative Feedback',
    'feedback.dialog.question.positive': 'What did you enjoy?',
    'feedback.dialog.question.negative': 'What could we improve?',
    'feedback.dialog.notes': 'Additional comments',
    'feedback.dialog.submit': 'Submit',
    'feedback.dialog.cancel': 'Cancel',
    'feedback.dialog.notes.placeholder': 'Type your comments here...',
    'feedback.toast.success': 'Thank you for your feedback!',
    'feedback.thumbsUp.aria': 'Thumbs up',
    'feedback.thumbsDown.aria': 'Thumbs down',
    'feedback.title': 'Share your feedback',
    'feedback.positive.title': 'What did you like?',
    'feedback.negative.title': 'What could be improved?',
    'feedback.submitButton': 'Submit Feedback',
    'feedback.positive.options': '',
    'feedback.negative.options': '',
  },
  arrays: {
    'welcome.examples': [
      {
        text: 'Find the best hiking trails',
        systemPrompt: 'Show me the best hiking trails for beginners.',
        backgroundColor: '#e8651a',
        image: 'https://wknd-adventures.run.place/media_1bac413f3fb7872aec76c9a452e2f43fd6cfa6ff1.jpg?width=900&format=jpg&optimize=medium',
      },
      {
        text: 'Learn about ultralight gear',
        systemPrompt: 'What are the essentials for ultralight backpacking?',
        backgroundColor: '#eb7c3c',
        image: 'https://wknd-adventures.run.place/media_1e56ff87aeb7dc7d3d4eb4acd41d468f583a00303.jpg?width=900&format=jpg&optimize=medium',
      },
      {
        text: 'Plan a climbing trip',
        systemPrompt: 'Help me plan a climbing trip to Yosemite.',
        backgroundColor: '#ef935f',
        image: 'https://wknd-adventures.run.place/media_1e4b49be43a70d306b1c312d0d78dd369b5ccce40.jpg?width=900&format=jpg&optimize=medium',
      },
      {
        text: 'Discover winter expeditions',
        systemPrompt: 'What are the best winter expeditions for experienced climbers?',
        backgroundColor: '#f2aa81',
        image: 'https://wknd-adventures.run.place/media_137e525a8479336997a84917d2ad521f873e4df22.jpg?width=900&format=webp&optimize=medium',
      },
    ],
    'feedback.positive.options': ['Helpful information', 'Easy to use', 'Great design', 'Fast responses', 'Other'],
    'feedback.negative.options': ['Confusing interface', 'Slow responses', 'Missing information', 'Technical issues', 'Other'],
  },
  assets: {
    icons: {
      company: '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="#0f1a14" stroke-width="1.8"><circle cx="12" cy="12" r="9"/><path d="m15.5 8.5-2 5-5 2 2-5z"/></svg>',
    },
  },
  visualProfile: { sendIconIconColor: '#ffffff', sendIconBackgroundColor: '#0f1a14' },
  theme: {
    '--welcome-input-order': '3',
    '--welcome-cards-order': '2',
    '--welcome-heading-size-desktop': '1.75rem',
    '--welcome-heading-size-mobile': '1.25rem',
    '--welcome-heading-weight': '700',
    '--welcome-heading-text-align': 'center',
    '--welcome-subheading-size-desktop': '1rem',
    '--welcome-subheading-size-mobile': '1rem',
    '--welcome-subheading-text-align': 'center',
    '--welcome-padding': '1rem',
    '--logo-size-desktop': '48px',
    '--logo-size-mobile': '48px',
    '--logo-margin-bottom-desktop': '8px',
    '--logo-margin-bottom-mobile': '8px',
    '--prompt-suggestion-background': '#0f1a14',
    '--prompt-suggestion-background-hover': '#0f1a14',
    '--prompt-suggestion-text-color': '#ffffff',
    '--prompt-suggestion-border-color': '#0f1a14',
    '--font-family': 'var(--body-font-family, system-ui, sans-serif)',
    '--color-primary': '#e8651a',
    '--color-text': '#0f1a14',
    '--line-height-body': '1.6',
    '--main-container-background': '#ffffff',
    '--input-height': '48px',
    '--input-height-mobile': '48px',
    '--input-border-radius': '8px',
    '--input-border-radius-mobile': '6px',
    '--input-background': '#f4f2ef',
    '--input-outline-color': '#d9d9d9',
    '--input-outline-width': '1px',
    '--input-box-shadow': '0 2px 4px rgba(0, 0, 0, 0.1)',
    '--input-focus-outline-width': '2px',
    '--input-focus-outline-color': '#e8651a',
    '--input-font-size': '1rem',
    '--input-font-weight': '400',
    '--input-text-color': '#0f1a14',
    '--input-button-height': '44px',
    '--input-button-width': '44px',
    '--submit-button-fill-color': '#ffffff',
    '--submit-button-fill-color-disabled': '#CCCCCC',
    '--color-button-submit': '#0f1a14',
    '--color-button-submit-hover': '#0f1a14',
    '--input-button-border-radius': '8px',
    '--button-disabled-background': '#F0F0F0',
    '--disclaimer-color': '#0f1a14',
    '--disclaimer-font-size': '0.875rem',
    '--disclaimer-font-weight': '400',
    '--message-user-background': '#0f1a14',
    '--message-user-text': '#ffffff',
    '--message-border-radius': '8px',
    '--message-padding': '1rem',
    '--message-concierge-background': '#f3f3f3',
    '--message-concierge-text': '#000000',
    '--message-max-width': '100%',
    '--chat-interface-max-width': '100%',
    '--message-blocker-height': '48px',
    '--loading-message-background': '#d9d9d9',
    '--loading-dot-background': '#626262',
    '--color-text-muted': '#626262',
    '--citations-text-font-weight': '600',
    '--citations-desktop-button-font-size': '0.875rem',
    '--feedback-icon-btn-background': '#f4f2ef',
    '--feedback-icon-btn-hover-background': '#e8651a',
    '--feedback-icon-btn-size-desktop': '44px',
    '--feedback-container-gap': '1rem',
    '--multimodal-card-box-shadow': '0 2px 4px rgba(0, 0, 0, 0.1)',
    '--border-radius-card': '8px',
    '--button-height-s': '44px',
    '--button-primary-background': '#0f1a14',
    '--button-primary-text': '#ffffff',
    '--button-primary-hover': '#0f1a14',
    '--button-secondary-border': '#e8651a',
    '--button-secondary-text': '#0f1a14',
    '--button-secondary-hover': '#0f1a14',
    '--color-button-secondary-hover-text': '#ffffff',
    '--privacy-notice-background': '#f4f2ef',
    '--privacy-notice-padding': '1rem',
    '--privacy-notice-title-color': '#626262',
    '--privacy-notice-text-color': '#626262',
    '--privacy-notice-text-font-size': '0.875rem',
    '--privacy-notice-title-font-size': '1rem',
    '--message-concierge-link-decoration': 'underline',
    '--color-secondary': '#0f1a14',
    '--prompt-suggestion-button-background': '#d9d9d9',
    '--prompt-pill-background': '#0f1a14',
    '--prompt-pill-background-hover': '#0f1a14',
    '--prompt-pill-icon-color': '#ffffff',
    '--prompt-pill-padding': '8px 12px',
    '--button-primary-mobile-background': '#0f1a14',
    '--button-primary-mobile-hover': '#0f1a14',
    '--main-container-mobile-background': '#ffffff',
    '--message-concierge-border-width': '1px',
    '--message-concierge-link-color': '#0f1a14',
    '--prompt-suggestion-button-border-radius': '999px',
    '--prompt-suggestion-button-padding': '0.5rem 1rem',
    '--prompt-suggestions-container-gap': '0.5rem',
    '--card-background': '#e8651a',
    '--card-text-font-size': '1rem',
    '--card-text-padding': '1rem',
    '--chat-container-background': '#ffffff',
    '--message-blocker-background': '#ffffff',
    '--card-text-color': '#ffffff',
    '--prompt-pill-border-color': '#e8651a',
    '--prompt-pill-text-color': '#ffffff',
    '--prompt-suggestion-button-text-color': '#0f1a14',
    '--prompt-suggestion-button-background-hover': '#f4f2ef',
    '--welcome-heading-text-color': '#000000',
    '--welcome-subheading-text-color': '#000000',
    '--welcome-header-order': '1',
    '--prompt-suggestions-flex-direction': 'row',
    '--prompt-suggestions-flex-wrap': 'wrap',
  },
};
